AWSTemplateFormatVersion: 2010-09-09
Description: lambda function creation
Resources:
  Lambda1CreatTrip:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: createtrip1
      Role: arn:aws:iam::256922262925:role/LabRole
      Code:
        S3Bucket: tripflexbackend
        S3Key: createTrip.zip
      Runtime: python3.9
      Timeout: 60
      TracingConfig:
        Mode: Active
      Handler: index.handler
  Lambda2checkSubtrip:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: checkSubtrip1
      Role: arn:aws:iam::256922262925:role/LabRole
      Code:
        S3Bucket: tripflexbackend
        S3Key: checkSubtrip.zip
      Runtime: python3.9
      Timeout: 60
      TracingConfig:
        Mode: Active
      Handler: index.handler
  Lambda3getSubtrip:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: getSubTrip1
      Role: arn:aws:iam::256922262925:role/LabRole
      Code:
        S3Bucket: tripflexbackend
        S3Key: getSubTrip.zip
      Runtime: python3.9
      Timeout: 60
      TracingConfig:
        Mode: Active
      Handler: index.handler
  Lambda4createPayment:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: createPayment1
      Role: arn:aws:iam::256922262925:role/LabRole
      Code:
        S3Bucket: tripflexbackend
        S3Key: createPayment.zip
      Runtime: python3.9
      Timeout: 60
      TracingConfig:
        Mode: Active
      Handler: index.handler
  Lambda5getDetailedTrip:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: getDetailedTrip1
      Role: arn:aws:iam::256922262925:role/LabRole
      Code:
        S3Bucket: tripflexbackend
        S3Key: getDetailedTrip.zip
      Runtime: python3.9
      Timeout: 60
      TracingConfig:
        Mode: Active
      Handler: index.handler
  Lambda6getPayment:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: getPayment1
      Role: arn:aws:iam::256922262925:role/LabRole
      Code:
        S3Bucket: tripflexbackend
        S3Key: getPayment.zip
      Runtime: python3.9
      Timeout: 60
      TracingConfig:
        Mode: Active
      Handler: index.handler
  Lambda7getTrips:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: getTrips1
      Role: arn:aws:iam::256922262925:role/LabRole
      Code:
        S3Bucket: tripflexbackend
        S3Key: getTrips.zip
      Runtime: python3.9
      Timeout: 60
      TracingConfig:
        Mode: Active
      Handler: index.handler
  Lambda8s3FileUpload:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: s3FileUpload1
      Role: arn:aws:iam::256922262925:role/LabRole
      Code:
        S3Bucket: tripflexbackend
        S3Key: s3FileUpload.zip
      Runtime: nodejs16.x
      Timeout: 60
      TracingConfig:
        Mode: Active
      Handler: index.handler
  Lambda9snsSubscribe:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: snsSubscribe1
      Role: arn:aws:iam::256922262925:role/LabRole
      Code:
        S3Bucket: tripflexbackend
        S3Key: snsSubscribe.zip
      Runtime: python3.9
      Timeout: 60
      TracingConfig:
        Mode: Active
      Handler: index.handler