AWSTemplateFormatVersion: "2010-09-09"

Resources:
    createTrip:
        Type: "AWS::Lambda::Function"
        Properties:
            Description: "Creating a Trip"
            FunctionName: "createTrip2"
            Handler: "lambda_function.lambda_handler"
            Code: 
                S3Bucket: "createtrip"
                S3Key: "createTrip-72f7e757-5341-449b-b65b-d49d4ce56a9d.zip"
            MemorySize: 128
            Role: "arn:aws:iam::288298330492:role/LabRole"
            Runtime: "python3.9"
            Timeout: 30

            